USE [master]
GO

/****** Object:  Database [otomasyon]    Script Date: 6.02.2023 12:03:29 ******/
CREATE DATABASE [otomasyon]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'otomasyon', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\otomasyon.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'otomasyon_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\otomasyon_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [otomasyon].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [otomasyon] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [otomasyon] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [otomasyon] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [otomasyon] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [otomasyon] SET ARITHABORT OFF 
GO

ALTER DATABASE [otomasyon] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [otomasyon] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [otomasyon] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [otomasyon] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [otomasyon] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [otomasyon] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [otomasyon] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [otomasyon] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [otomasyon] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [otomasyon] SET  DISABLE_BROKER 
GO

ALTER DATABASE [otomasyon] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [otomasyon] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [otomasyon] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [otomasyon] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [otomasyon] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [otomasyon] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [otomasyon] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [otomasyon] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [otomasyon] SET  MULTI_USER 
GO

ALTER DATABASE [otomasyon] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [otomasyon] SET DB_CHAINING OFF 
GO

ALTER DATABASE [otomasyon] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [otomasyon] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [otomasyon] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [otomasyon] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [otomasyon] SET QUERY_STORE = OFF
GO

ALTER DATABASE [otomasyon] SET  READ_WRITE 
GO

